### ISSUE TITLE
文件似乎有錯誤

### ISSUE THREAD

**Issue by tim80411** [alfredotang/dotfiles#1]
## 系統資訊：
1. CPU: m1 pro
2. version: 13.2.1

## 錯誤資訊
在README.md關於安裝的一行是

```
sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/alfredotang/dotfiles/master/macOS/install.sh)"
```

在第一個階段安裝homebrew時會出錯，錯誤的資訊為`don't run this as root`

## 問題解決
把sudo刪掉就會正常了XD

**Comment by alfredotang** [comment]
thanks for debugging, I'll fix it ASAP
